version: "3"
services:
  pgdm-api-rest:
    image: pgdm-api
    env_file: 
      - build/docker/env.env
    build:
      context: .
      dockerfile: build/docker/Dockerfile
      args:
        - SERVER=rest
    ports:
      - "3333:3333"